Fix address and prev health number issues in enrolment
bcgov/MOH-MSP-Enrolment pull request #43
Opened 2021-08-30 22:47 UTC by bryce-mcmath

### Please check if the PR fulfills these requirements:

- [x] After these changes, the app was run and still works as expected
- [ ] Unit tests for these changes were added (if applicable)
- [x] All existing unit tests were run and still pass

### Please specify the type of change this PR introduces (Bug fix, feature addition, content update, chore, etc.):
Bug fix. `prevHealthNumber` should reference a health number from another province, not their previous BC PHN
Additionally, should their be no mailing address, their residential address will be filled in instead (for enrolment this time)

### Additional Notes:

2021-08-30 23:59 UTC, cyrilbravo approved these changes
Changes in enrolment service looks good. Approved :)

2021-08-31 00:27 UTC, harrymaynard-maximus requested changes

2021-08-31 00:27 UTC, harrymaynard-maximus commented on msp/package.json
> +  "version": "3.4.3",
You'll need to include the update to "package-lock.json" to use the updated version (run "npm install"). I think OpenShift might throw an error if this gets deployed as is.

2021-08-31 19:48 UTC, harrymaynard-maximus approved these changes
Looks good.

2021-08-31 19:50 UTC, merged